<?php
/**
 * Created by PhpStorm.
 * User: hocvt
 * Date: 3/31/16
 * Time: 10:40
 */

namespace App\Core\MediaProcess\Formats;


use FFMpeg\Format\Video\X264;

class Mp4Format extends X264{
	public function __construct( $audioCodec = 'libfdk_aac', $videoCodec = 'libx264' ) {
		parent::__construct( $audioCodec, $videoCodec ); // TODO: Change the autogenerated stub
	}
	
}