<?php namespace App\Http\Middleware;

use Closure;
use Illuminate\Contracts\Encryption\Encrypter;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as BaseVerifier;

class VerifyCsrfToken extends BaseVerifier {

	protected $except = ['idvg/change'];

	public function __construct(Encrypter $encrypter)
	{
		parent::__construct($encrypter); // TODO: Change the autogenerated stub
		$this->except[] = config('idvg.unibee.url_event');
		$this->except[] = '/api/youtube/*';
		$this->except[] = '/api/bpn';
		$this->except[] = '/search/api?*';
		$this->except[] = '/api/start_video_view_log*';
        $this->except[] = '/api-myedu/exams';
	}


	/**
	 * Handle an incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  \Closure  $next
	 * @return mixed
	 */
	public function handle($request, Closure $next)
	{
		return parent::handle($request, $next);
	}

}
